CREATE TABLE book
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(30),
    description TEXT,
    price NUMERIC(5, 2) CHECK (price >= 0.1 AND price <= 500) NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
)